-- Drop table if exists
DROP TABLE fifa_stats2;

-- Create new table
CREATE TABLE fifa_stats2 (
	Player_Name varchar,
	Overall int,
	Club varchar,
	League varchar,
	Nationality varchar,
	Position varchar,
	Age int	,
	Height_cm int,
	Weight_kg int,
	Pace int,
	Acceleration int,
	Sprint_Speed int,
	Dribbling int,
	Agility int,
	Balance int,
	Reactions int,
	Ball_Control int,
	Composure int,
	Shooting int,
	Positioning int,
	Finishing int,
	Shot_Power int,
	Long_Shots int,
	Volleys int,
	Penalties int,
	Passing	int,
	Vision int,
	Crossing int,
	Free_Kick int,
	Short_Pass int,
	Long_Pass int,
	Pass_Curve int,
	Defending int,
	Interceptions int,
	Heading int,
	Marking int,
	Standing_Tackle int,
	Sliding_Tackle int,
	Physicality int,
	Jumping int,
	Stamina int,
	Strength int,
	Aggression int,
	Diving int,
	Reflexes int,
	Handling int,
	Speed int,
	Kicking int,
	Positoning int,
	Preferred_Foot varchar,
	Attacking_Workrate varchar,	
	Defensive_Workrate varchar,
	Weak_Foot int,
	Skill_Moves int,
	CB int,
	RB int,
	LB int,
	RWB	int,
	LWB int,
	CDM int,
	CM int,
	RM int,
	LM int,
	CAM int,
	CF int,
	RF int,
	LF int,
	RW int,
	LW int,
	ST int
);


-- View table columns and datatypes
SELECT * FROM fifa_stats2;